### ISSUE TITLE
ArgumentNullException: Az érték nem lehet NULL.
Paraméter neve: value

### ISSUE THREAD

**Issue by Atrejoe** [Atrejoe/SPA-Call-Manager-Pro#27]
View details in Rollbar: [https://rollbar.com/SPACallmanagerPro/SPA-Callmanager-Pro/items/29/](https://rollbar.com/SPACallmanagerPro/SPA-Callmanager-Pro/items/29/)

```
Traceback (most recent call last):
  File "Microsoft.Win32.RegistryKey", line 3, in SetValue(System.String name, System.Object value, Microsoft.Win32.RegistryValueKind valueKind)
  File "Microsoft.Win32.Registry", line 15, in SetValue(System.String keyName, System.String valueName, System.Object value, Microsoft.Win32.RegistryValueKind valueKind)
  File "C:\Projects\SPA-Call-Manager-Pro\Cisco\ModMain.vb", line 139, in SetStoredSettings(Pss.Cisco.Settings storedPhoneSettings)
ArgumentNullException: Az érték nem lehet NULL.
Paraméter neve: value
```

**Comment by Atrejoe** [comment]
Possible duplicate of #29
