### ISSUE TITLE
ArgumentNullException: Az érték nem lehet NULL.
Paraméter neve: value

### ISSUE THREAD

**Issue by Atrejoe** [Atrejoe/SPA-Call-Manager-Pro#28]
View details in Rollbar: [https://rollbar.com/SPACallmanagerPro/SPA-Callmanager-Pro/items/30/](https://rollbar.com/SPACallmanagerPro/SPA-Callmanager-Pro/items/30/)

```
Traceback (most recent call last):
  File "C:\Projects\SPA-Call-Manager-Pro\Cisco\ModMain.vb", line 152, in SetStoredSettings(Pss.Cisco.Settings storedPhoneSettings)
  File "C:\Projects\SPA-Call-Manager-Pro\Cisco\FrmSetup.vb", line 34, in Button1_Click(System.Object sender, System.EventArgs e)
ArgumentNullException: Az érték nem lehet NULL.
Paraméter neve: value
```

**Comment by Atrejoe** [comment]
Possible duplicate of #29
