### ISSUE TITLE
ArgumentNullException: Value cannot be null.
Parameter name: hostname

### ISSUE THREAD

**Issue by Atrejoe** [Atrejoe/SPA-Call-Manager-Pro#31]
View details in Rollbar: [https://rollbar.com/SPACallmanagerPro/SPA-Callmanager-Pro/items/34/](https://rollbar.com/SPACallmanagerPro/SPA-Callmanager-Pro/items/34/)

```
Traceback (most recent call last):
  File "System.Net.Sockets.UdpClient", line 57, in Connect(System.String hostname, System.Int32 port)
  File "C:\Projects\SPA-Call-Manager-Pro\Cisco\ClsPhone.vb", line 310, in SendUdp(System.String message, System.String ipaddress, System.Int32 port)
ArgumentNullException: Value cannot be null.
Parameter name: hostnameTraceback (most recent call last):

UdpMessageException: Error while sending UDP message, see inner exception for details. UDP Message was : NOTIFY sip:@:0 SIP/2.0
Via: SIP/2.0/UDP :0
Max-Forwards: 70
From: <sip:WSROBERT8@>;tag=1710726934
To: <sip:@>
Call-ID: 793415@
CSeq: 1 NOTIFY
Contact: <sip:WSROBERT8@:0>
Content-Type: application/x-spa-control
Event: x-spa-cti

<spa-control>
<newcall uri="+31854891240@$proxy" call="1" />
</spa-control>
```

**Comment by Atrejoe** [comment]
This occurred when the phone was initially offline. First the phone was not found at the designated ip address. The application did not re-check, and all controls were usable. When dialling a number, this error occurred. When opening the settings dialogue, everything was empty.
